spring:

  # DB μ„Έν…
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootSample
    username: root
    password: root
  
  #JSP μ„Έν…
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
